import = ["~/.config/alacritty/catppuccin-mocha.toml"]
[shell]

program = "/usr/bin/zsh"
args = ["-l"]

[window]

dimensions = { columns = 75, lines = 25}

[font]

normal = { family = "JetBrainsMonoNerdFont", style = "Medium" } 
bold = { family = "JetBrainsMonoNerdFont", style = "Bold" } 
italic = { family = "JetBrainsMonoNerdFont", style = "MediumItalic" }
bold_italic = { family = "JetBrainsMonoNerdFont", style = "BoldItalic" }
size = 10.00

[mouse]

hide_when_typing = true

